Michaelndula/ChurchCRM-Mobil

App.js
assets/css/styles.js
navigation/screens/Notes.js
navigation/screens/auth/LoginScreen.js
navigation/screens/auth/SignupScreen.js
navigation/screens/notes/NewNotes.js

@Michaelndula completion of the auth

completion of the auth

---

App.js
navigation/MainContainer.js
navigation/screens/More.js
navigation/screens/auth/LoginScreen.js
navigation/screens/auth/ProfileScreen.js
navigation/screens/auth/SignupScreen.js

Display Info on Profile Page

---

assets/css/styles.js
navigation/screens/HomeScreen.js
navigation/screens/Notes.js
navigation/screens/notes/NewNotes.js

Notes and NewNotes pages styled

Notes and NewNotes pages styled

---

App.js
assets/css/styles.js
navigation/MainContainer.js
navigation/screens/Notes.js
navigation/screens/auth/LoginScreen.js
navigation/screens/auth/ProfileScreen.js
navigation/screens/auth/SignupScreen.js
navigation/screens/notes/EditNotes.js
navigation/screens/notes/NewNotes.js

Notes creation and reading of data

---

App.js
assets/css/EventsScreen.js
assets/css/MoreScreen.js
assets/css/SettingScreen.js
navigation/screens/EventsScreen.js
navigation/screens/More.js
navigation/screens/auth/ProfileScreen.js
navigation/screens/auth/SettingScreen.js
package-lock.json
package.json

@Michaelndula @Njeri-Ngugi theme update

theme update

---

.env
assets/css/SettingScreen.js
config/theme.js
navigation/screens/auth/SettingScreen.js

@Michaelndula @Njeri-Ngugi @mathewwahome The setting screen ui

The setting screen ui

---

App.js
assets/css/styles.js
navigation/screens/HomeScreen.js
navigation/screens/Notes.js
navigation/screens/SermonNotes.js
navigation/screens/SermonsScreen.js
navigation/screens/auth/LoginScreen.js
navigation/screens/auth/ProfileScreen.js
navigation/screens/auth/SignupScreen.js
navigation/screens/notes/NewNotes.js

Linking sermons page to sermon notes page.

Sermons and Sermon Notes Pages

---

App.js
navigation/screens/HomeScreen.js
navigation/screens/announcements/AnnouncementView.js

@Njeri-Ngugi @Michaelndula announcement view

announcement view

---

App.js
assets/css/styles.js
navigation/MainContainer.js
navigation/screens/HomeScreen.js
navigation/screens/Notes.js
navigation/screens/SermonNotes.js
navigation/screens/SermonsScreen.js
navigation/screens/auth/LoginScreen.js
navigation/screens/auth/SignupScreen.js
navigation/screens/notes/NewNotes.js

PDF in SermonNotes page

---

package-lock.json
package.json
src/actions/index.js
src/actions/user.js
src/hooks/HandleLogin.js
src/hooks/network.js
src/screens/auth/LoginScreen.js
src/storage/db.js
src/ui/components/container.js
src/ui/components/empty_list.js
src/ui/components/icon.js
src/ui/header.js
src/utilities/colors.js
src/utilities/validation.js

@mathewwahome @Njeri-Ngugi @Methewwahome Adding hooks to avoid repetition on api post and get calls, Adding local storage and utilities folder

Adding hooks to avoid repetition on api post and get calls, Adding local storage and utilities folder

---

src/screens/auth/LoginScreen.js

removed the primary color

---

src/hooks/HandleApis.js
src/screens/HomeScreen.js
src/screens/auth/LoginScreen.js

@mathewwahome @Njeri-Ngugi @Methewwahome I have added more reusable hooks, cleaned up the Hope Screen and added more functionalities to check if data exits, If not display a data does not exist message.

Adding reusable hooks, brushing up the Home

---

src/assets/css/SermonsScreen.js
src/screens/SermonsScreen.js

Sermon Screen UI

---

package-lock.json
package.json
src/assets/css/Global.js
src/hooks/HandleApis.js
src/screens/view/VideoPlayer.js
yarn.lock

@Michaelndula @Njeri-Ngugi video player

video player

---

android/app/build.gradle
src/assets/css/AuthScreens.js
src/assets/css/Color.js
src/assets/css/styles.js
src/hooks/CustomTestInput.js
src/hooks/HandleApis.js
src/hooks/HandleAuth.js
src/hooks/HandleSignup.js
src/screens/Notes.js
src/screens/auth/LoginScreen.js
src/screens/auth/SignupScreen.js
src/screens/notes/NewNotes.js

@Michaelndula notes page and new notes - updated the function for adding new notes and also displaying all the notes

notes page and new notes

---

App.js
src/hooks/HandleAuth.js
src/screens/auth/LoginScreen.js

@Michaelndula Completion of the Auth From @Njeri-Ngugi

Completion of the Auth From @Njeri-Ngugi

---

App.js
src/MainContainer.js
src/assets/css/styles.js
src/screens/Notes.js
src/screens/auth/SignupScreen.js
src/screens/notes/NewNotes.js

Saving and displaying user notes plus New Notes UI

Saving and displaying user notes plus New Notes UI

---

src/assets/css/Global.js
src/assets/css/HomeScreen.js
src/screens/view/AnnouncementView.js

@Michaelndula @Njeri-Ngugi Announcements update

Announcements update

---

.npmrc
App.js
babel.config.js
package-lock.json
package.json
src/MainContainer.js
src/assets/css/EventsScreen.js
src/assets/css/Global.js
src/hooks/CustomTestInput.js
src/navigation/BottomTabNavigator.js
src/navigation/DrawerNavigator.js
src/navigation/stack-navigators/HomeStackNavigator.js
src/navigation/stack-navigators/SermonsStackNavigator.js
src/screens/EventsScreen.js
src/screens/ListView/Events.js
src/screens/Notes.js
src/screens/auth/LoginScreen.js
src/screens/auth/ProfileScreen.js
src/screens/view/EventView.js
src/screens/view/VideoPlayer.js
yarn.lock

@Michaelndula @Njeri-Ngugi  navigation drawer creation

navigation drawer

---

App.js
package-lock.json
package.json
src/MainContainer.js
src/navigation/DrawerNavigator.js
src/screens/ListView/Sermons.js
src/screens/Notes.js
src/screens/notes/NewNotes.js
yarn.lock

@Michaelndula Sorting out some errors with the Notes Page and New Notes page

Sorting out some errors with the Notes Page and New Notes page

---

App.js
src/MainContainer.js
src/assets/css/DrawerNavigatorcss.js
src/assets/css/ProfileScreen.js
src/hooks/HandleApis.js
src/navigation/DrawerNavigator.js
src/screens/Notes.js
src/screens/SermonNotes.js
src/screens/auth/ProfileScreen.js

@Michaelndula @Njeri-Ngugi drawer profile display

drawer profile display

---

src/MainContainer.js
src/assets/css/AuthScreens.js
src/assets/css/DrawerNavigatorcss.js
src/assets/css/Login.js
src/assets/css/MoreScreen.js
src/navigation/DrawerNavigator.js
src/screens/More.js
src/screens/auth/ForgotPassword.js
src/screens/auth/LoginScreen.js

@Michaelndula @Njeri-Ngugi  Icon error solving

Icon error solving

---

android/gradle.properties
src/hooks/HandleApis.js
src/navigation/DrawerNavigator.js

Returned changes in drawer navigator

Returned changes in drawernavigator

---

App.js
src/hooks/HandleAuth.js
src/navigation/BottomTabNavigator.js
src/navigation/DrawerNavigator.js
src/navigation/stack-navigators/Home.js
src/screens/More.js
src/screens/auth/LoginScreen.js
src/screens/auth/ProfileScreen.js

Login resolved

---

src/hooks/HandleAuth.js
src/navigation/DrawerNavigator.js
src/screens/auth/LoginScreen.js
src/screens/auth/ProfileScreen.js

logout copletion

---

App.js
src/hooks/HandleAuth.js
src/screens/More.js

@Michaelndula Retreave userID from storage

Retreave userID from storage

---

App.js
src/screens/Notes.js
src/screens/notes/EditNotes.js

@Michaelndula @Njeri-Ngugi Start of edit notes the fetch of the specific note and display of its content

Start of edit notes

---

src/assets/css/HomeScreen.js
src/screens/VerseOfTheDay/VerseOfTheDay.js
src/screens/view/VideoPlayer.js

Verse of the day Bakground loading image solved

Verse of the day Bakground loading image solved

---

App.js
src/LandingScreen.js
src/assets/css/styles.js
src/hooks/HandleApis.js
src/screens/Notes.js
src/screens/notes/EditNotes.js
src/screens/notes/NewNotes.js
src/screens/notes/ViewNote.js

@Michaelndula @Njeri-Ngugi @mathewwahome

Co-authored-by: Njeri <Njeri-Ngugi@users.noreply.github.com>

---

src/assets/css/AuthScreens.js
src/screens/auth/ForgotPassword.js

Reset Password page restyled

---

App.js
src/hooks/HandleApis.js
src/screens/Notes.js
src/screens/notes/EditNotes.js
src/screens/notes/NewNotes.js
src/screens/notes/ViewNote.js

Notes reloading sorted

---

App.js
src/navigation/BottomTabNavigator.js
src/navigation/DrawerNavigator.js

Notes reload with bottom tab navigator

Notes reload with bottom tab navigator

---

App.js
src/assets/css/AuthScreens.js
src/assets/css/ProfileScreen.js
src/hooks/CustomTestInput.js
src/hooks/HandleApis.js
src/hooks/HandleAuth.js
src/screens/auth/ChangePassword.js
src/screens/auth/LoginScreen.js
src/screens/auth/ProfileScreen.js

@Michaelndula @Njeri-Ngugi change passsword

change passsword

---

src/assets/css/Global.js
src/assets/css/HomeScreen.js
src/hooks/HandleApis.js
src/screens/ListView/SermonNotes.js
src/screens/view/SermonNotesView.js

Sermon notes changes

---

package-lock.json
package.json
src/assets/css/GlobalCss.js
src/assets/css/ProfileScreen.js
src/screens/More.js
src/screens/auth/ProfileScreen.js
src/screens/auth/SettingScreen.js

@Michaelndula @Njeri-Ngugi profile update

profile update

---

src/assets/css/Global.js
src/assets/css/HomeScreen.js
src/hooks/HandleApis.js
src/screens/view/SermonNotesView.js

Sermon Notes View Page error solved

Sermon Notes View Page error solved

---

App.js
src/hooks/HandleApis.js
src/hooks/HandleAuth.js
src/screens/Notes.js
src/screens/auth/ForgotPassword.js
src/screens/auth/NewPassword.js
src/screens/auth/ResetCode.js

@Michaelndula @Njeri-Ngugi Reset of password using a code.

Reset of password using a code.

---

src/assets/css/AuthScreens.js

@Michaelndula @Njeri-Ngugi completion of the code reset password

completion of the code reset password

---

src/assets/css/ProfileScreen.js
src/assets/css/styles.js
src/screens/Notes.js
src/screens/auth/ProfileScreen.js
src/screens/notes/EditNotes.js
src/screens/notes/NewNotes.js

@Njeri-Ngugi @Michaelndula initial height introduction on note type

initial height introduction on note type

---

src/navigation/DrawerNavigator.js
src/screens/auth/ProfileScreen.js

Only include profile photo if it exists

---

App.js
src/assets/css/Global.js
src/hooks/HandleAuth.js
src/screens/ListView/Announcements.js
src/screens/auth/LoginScreen.js
src/screens/view/AnnouncementView.js
src/screens/view/SermonNotesView.js
src/screens/view/VideoPlayer.js

Token expiry, sermons and announcement recommendations

Token expiry, sermons and announcement recommendations

---

App.js
src/assets/css/EventsScreen.js
src/assets/css/Global.js
src/assets/css/ProfileScreen.js
src/assets/css/SermonsPage.js
src/navigation/BottomTabNavigator.js
src/navigation/DrawerNavigator.js
src/screens/ListView/Announcements.js
src/screens/ListView/Events.js
src/screens/ListView/SermonNotes.js
src/screens/ListView/Sermons.js
src/screens/Notes.js
src/screens/auth/ProfileScreen.js
src/screens/home/HomeScreen.js
src/screens/sermons/SermonScreen.js
src/screens/view/AnnouncementView.js
src/screens/view/EventView.js
src/screens/view/Item_Views/AnnouncementItem.js
src/screens/view/Item_Views/EventItem.js
src/screens/view/Item_Views/SermonItem.js
src/screens/view/Item_Views/SermonNoteItem.js
src/screens/view/SermonNotesView.js
src/screens/view/VideoPlayer.js

- Making sermons, announcements, sermon notes and events reusable

Making sermons, announcements, sermon notes and events reusable
